// Runtime appearance settings for the Customise tab (goal #4).
//
// Two kinds of setting live here:
//
//   * Hyprland knobs (blur, opacities, gaps, animations) — applied live
//     through HyprlandService, which speaks `hyprctl eval` because this
//     machine runs Hyprland with a Lua config (finding F2).
//   * kitty knobs (cursor_trail, background_opacity, font_size) — written into
//     kitty/user-settings.conf, which kitty.conf includes. That file is
//     gitignored, exactly like current-theme.conf, so runtime changes never
//     dirty the repo. After a write kitty is signalled with SIGUSR1 to reload.
//
// Everything is mirrored to ~/.local/state/quickshell/settings.json and
// re-applied on startup, so a shell restart restores what you chose.
pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io

QtObject {
    id: root

    readonly property string home: Quickshell.env("HOME")
    readonly property string stateDir: home + "/.local/state/quickshell"
    readonly property string stateFile: stateDir + "/settings.json"
    readonly property string kittyFile: home + "/.config/kitty/user-settings.conf"

    // ── Hyprland-backed values ──────────────────────────────────────────────
    property bool   blurEnabled: true
    property int    blurSize: 8
    property int    blurPasses: 2
    property real   activeOpacity: 1.0
    property real   inactiveOpacity: 0.9
    property bool   animationsEnabled: true
    property int    gapsIn: 5
    property int    gapsOut: 10
    property int    rounding: 10

    // ── kitty-backed values ─────────────────────────────────────────────────
    property int    cursorTrail: 3
    property real   backgroundOpacity: 0.85
    property real   fontSize: 12

    // ── Shell-only values ───────────────────────────────────────────────────
    // Consumed directly by Metrics/Theme at runtime.
    property int    barHeight: 40
    property int    animDuration: 320
    // Control center opens on hover of the notch (true) or on click (false).
    property bool   ccOpenOnHover: false

    // ── Applying ────────────────────────────────────────────────────────────

    function applyHyprland() {
        HyprlandService.setBlur("enabled", blurEnabled)
        HyprlandService.setBlur("size", blurSize)
        HyprlandService.setBlur("passes", blurPasses)
        HyprlandService.setDecoration("active_opacity", activeOpacity.toFixed(2))
        HyprlandService.setDecoration("inactive_opacity", inactiveOpacity.toFixed(2))
        HyprlandService.setDecoration("rounding", rounding)
        HyprlandService.setGeneral("gaps_in", gapsIn)
        HyprlandService.setGeneral("gaps_out", gapsOut)
        HyprlandService.setAnimationsEnabled(animationsEnabled)
        // Our own surfaces need the layerrule re-stated when blur toggles.
        HyprlandService.setLayerBlur(blurEnabled)
    }

    // kitty reads this file on SIGUSR1; rewriting the whole thing keeps the
    // file honest rather than appending duplicates on every change.
    function applyKitty() {
        var body = "# Generated by the Quickshell Customise tab. Do not edit.\n"
                 + "# kitty.conf includes this file; it is gitignored.\n"
                 + "cursor_trail " + cursorTrail + "\n"
                 + "background_opacity " + backgroundOpacity.toFixed(2) + "\n"
                 + "font_size " + fontSize.toFixed(1) + "\n"
        _kittyWrite.command = ["bash", "-c",
            "mkdir -p \"$(dirname \"$1\")\" && printf '%s' \"$2\" > \"$1\" && " +
            "pkill -SIGUSR1 -x kitty 2>/dev/null; true", "_", root.kittyFile, body]
        _kittyWrite.running = true
    }

    property Process _kittyWrite: Process {}

    // ── Persistence ─────────────────────────────────────────────────────────

    function snapshot() {
        return {
            blurEnabled: root.blurEnabled,
            blurSize: root.blurSize,
            blurPasses: root.blurPasses,
            activeOpacity: root.activeOpacity,
            inactiveOpacity: root.inactiveOpacity,
            animationsEnabled: root.animationsEnabled,
            gapsIn: root.gapsIn,
            gapsOut: root.gapsOut,
            rounding: root.rounding,
            cursorTrail: root.cursorTrail,
            backgroundOpacity: root.backgroundOpacity,
            fontSize: root.fontSize,
            barHeight: root.barHeight,
            animDuration: root.animDuration,
            ccOpenOnHover: root.ccOpenOnHover
        }
    }

    function save() {
        _save.command = ["bash", "-c",
            "mkdir -p '" + root.stateDir + "' && printf '%s' \"$1\" > '" + root.stateFile + "'",
            "_", JSON.stringify(root.snapshot())]
        _save.running = true
    }

    // Called after every UI change: persist, then push to Hyprland/kitty.
    function commit() {
        save()
        applyHyprland()
        applyKitty()
    }

    property Process _save: Process {}

    property Process _load: Process {
        command: ["cat", root.stateFile]
        stdout: StdioCollector { onStreamFinished: root._restore(text) }
    }

    function _restore(raw) {
        if (!raw)
            return
        try {
            var o = JSON.parse(raw)
            for (var k in o) {
                if (root[k] !== undefined)
                    root[k] = o[k]
            }
            root.applyHyprland()
            root.applyKitty()
        } catch (e) {
            console.log("SettingsService: bad state file:", e)
        }
    }

    // Restore the compiled-in defaults.
    function reset() {
        blurEnabled = true; blurSize = 8; blurPasses = 2
        activeOpacity = 1.0; inactiveOpacity = 0.9
        animationsEnabled = true; gapsIn = 5; gapsOut = 10; rounding = 10
        cursorTrail = 3; backgroundOpacity = 0.85; fontSize = 12
        barHeight = 40; animDuration = 320
        ccOpenOnHover = false
        commit()
    }

    Component.onCompleted: _load.running = true
}
